### ISSUE TITLE
Guide for removing swarm

### ISSUE THREAD

**Issue by michaeltoohig** [tiangolo/dockerswarm.rocks#1]
Love the website and easy to remember name. I'm currently not very well versed with all the aspects of using swarm and trying to learn more.

One thing I wish to do now is to remove my swarm and then rebuild it. I want to do it again to make sure I understand what I am doing and prepare for a production deployment but I'm sure there are other use cases for removing a swarm.

My problem is I'm not sure if `docker swarm leave` will return everything to the pre-swarm state. For example, after leaving swarm I see networks in `docker network ls` that appear to be from the swarm but I'm not sure. I see a `{MY_PROJECT_NAME}_default` network which could be from compose or something else.

Thank you.

**Comment by tiangolo** [comment]
Hey @michaeltoohig, sorry for the delay.

Actually, I'm not sure :man_shrugging: ...In that case, to test that, I would create a new VPS server (DigitalOcean, Linode, Vulture, GCP, AWS), set up everything, then remove it and start from scratch. For testing these things it has ended up being faster/easier.
