### ISSUE TITLE
Clarify GitLab CI Runner Doc

### ISSUE THREAD

**Issue by j7an** [tiangolo/dockerswarm.rocks#11]
I'm reading the docs on GitLab CI runner. The following is a bit confusing: 

> "If you are using GitLab, you can run a GitLab CI "runner" in your Docker Swarm mode cluster to test, build and deploy automatically your code."

Reading further down the doc does not instruct how to install the main GitLab CE Docker image and have it integrated with the runner. It sounds like the doc assumes the user will use GitLab's hosted service. Please clarify the docs if this is the case.

In the following it's not clear if I'm looking at the Traefik dashboard for GitLab, the hosted GitLab dashboard, or dockerized GitLab. Please clarify.

> In a web browser, go to the GitLab "Admin Area -> Runners" section.

**Comment by tiangolo** [comment]
There are several ways to install GitLab, the official way doesn't necessarily play very well with the rest of Docker.

The most popular alternative way to install it with Docker is with https://github.com/sameersbn/docker-gitlab.

I have a pending PR from some time ago here https://github.com/sameersbn/docker-gitlab/pull/1826, but it hasn't been merged yet.

That would be, in my opinion, the easiest way to install GitLab manually using these same tools.

> In a web browser, go to the GitLab "Admin Area -> Runners" section.

This refers to the "Admin Area" in your GitLab installation. hosted or installed. Not the Traefik dashboard.

**Comment by j7an** [comment]
Thanks. Sounds like running GitLab hosted with only the GL runner in Docker would require the least amount of resources.

And thanks for creating this great doc for Traefik and Docker Swarm.

**Comment by tiangolo** [comment]
Great! Thanks for reporting back and closing the issue.
