### ISSUE TITLE
Use `${VARIABLE:?Variable not found}` instead of ${VARIABLE} where needed

### ISSUE THREAD

**Issue by dmrty** [tiangolo/dockerswarm.rocks#14]
FYI, I've started to use `${VARIABLE:?Variable not found}` when there is no obvious default so that the deploy crash if the variable is not set: 
See docker reference on [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) for more info. 
Maybe that would make sense to change the `${VARIABLE}` or `${VARIABLE:-}` by `${VARIABLE:?}` for a more solid deploy process?

_Originally posted by @dmrty in https://github.com/tiangolo/dockerswarm.rocks/issues/12#issuecomment-491737577_

**Comment by tiangolo** [comment]
Good idea! Let's continue the discussion here.

**Comment by tiangolo** [comment]
Now that your PR is merged, I think we can close this issue, right @dmrty ?

**Comment by dmrty** [comment]
Indeed
