### ISSUE TITLE
Load config error: Get http://consul-leader:8500

### ISSUE THREAD

**Issue by rodrigosaraiva** [tiangolo/dockerswarm.rocks#16]
Traefik container is failing:

Load config error: Get http://consul-leader:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp 10.0.7.10:8500: i/o timeout, retrying in 434.838594ms

I am getting this error, trying to work with one manager and one worker node.

**Comment by tiangolo** [comment]
It seems that Traefik is not being able to communicate with Consul. So, it's possible that Consul has some error. Check the logs in the Consul service.

---

It's possible that you started more consul replicas than needed.

If you have less than 3 nodes, you can use `export CONSUL_REPLICAS=0`: https://dockerswarm.rocks/traefik/#preparation

That will start a single Consul with `-bootstrap`. That way there will be only one Consul, and it won't have problems trying to choose a leader if it knows he's the only one.

**Comment by rodrigosaraiva** [comment]
I manage that, I was trying to create swarm mode with external IP. I did without and it works.
Now I have one more problem with invalid certificates.

**Comment by tiangolo** [comment]
Cool! I'm glad you solved the first problem :man_shrugging: 

Thanks for reporting back and closing this issue.
