### ISSUE TITLE
Consul

### ISSUE THREAD

**Issue by fpieressa** [tiangolo/dockerswarm.rocks#17]
Hi team, I have one doubt with your implementation of traefik with Consul in HA, we are seeing you are using the following command argument for the traefik proxy: 

 --consul.endpoint="consul-leader:8500"

As I understand, it must use the following definition:

 --consul.endpoint="consul-replica:8500"

If not, I don't understand the fole of the consul-replica...  and if the consul-leader goes down, it will take some seconds to restart or start in another node....

Thanks!

Thanks!

**Comment by tiangolo** [comment]
I'm sorry, I'm not sure I understand your question...
