### ISSUE TITLE
Using Socat instead of exposing :/var/run/docker.sock in Traefik

### ISSUE THREAD

**Issue by pascaldes** [tiangolo/dockerswarm.rocks#18]
Hi, 
You made an amazing job here! I think your best practices are on target.

About [exposing ](https://github.com/tiangolo/dockerswarm.rocks/blob/master/docs/traefik.yml#L69)the docker socket. I read in the past that it's best practice to use **socat** to expose the docker socket. Before writing a PR, would you consider using socat?

This is how I do it in my stack:
- https://github.com/pascalandy/docker-stack-this/blob/master/traefik_stack5/toolproxy.yml#L21
- https://github.com/pascalandy/docker-stack-this/blob/master/traefik_stack5/toolproxy.yml#L74

Also, if you feel this is useless, I'd like to know your opinions about it.

Cheers!

**Comment by tiangolo** [comment]
Hi @pascaldes ! I haven't read about `socat` as part of Docker best practices.

It seems those links are no longer available. Do you have any other reference?
