### ISSUE TITLE
Add a section "Brevity plus" section

### ISSUE THREAD

**Issue by vlcinsky** [tiangolo/dockerswarm.rocks#21]
The text is very well written and is using proper level of brevity.

Anyway, in many cases there are good reasons to provide more details and to explain other considerations. Samples are issue #20 or #10 (I am sure, there will be more).

How to keep the main text easy to follow and at the same time provide necessary space for extra explanation?

I would recommend adding new section called "Brevity plus" which would introduce set of short chapters, each:
- explaining simple topic
- having easy to understand title
- possibly using some easy to remember tag (like `[envpswd]`, `[advertise-addr]` etc.)

The section would be one global one and would have introduction explaining, that this is the place to explain some concepts in more details, but not aiming to cover given topics completely and perfectly.

Sample content could be:

# Brevity plus
Brevity is key to making the text usable. But it has also some limits.

This page describes selected topics in a bit more detail to allow main text to be succinct and refer to extended information by simple link to relevant topic here.

On the other hand, this page does not try to cover given topics completely, it aims only on providing basic alternative and extended information. 

## [hashed_pswd] Hashed passwords without environmental variable
If you need to create hashed password, you may omit using env. variable and type it directly into prompt as follows:

            export HASHED_PASSWORD=$(openssl passwd -apr1)
            Password: <enter it here>
            Verifying - Password: <re-enter it here>

## [advertise-addr] Proper IP for `docker swarm init --advertise-addr <IP>`
When initializing docker swarm, command sometime asks for clarification, which IP address to use.

The key requirement is, given IP address must be visible to other nodes to be able to join.

In case you are using VPN (and all potential nodes are connected to it), it is often better to use IP from this VPN as it does not force docker swarm publishing sensitive ports to external Internet.

**Comment by tiangolo** [comment]
Thanks for the suggestion @vlcinsky !

I added a note to the docs with your alternative way to type passwords without putting them in an env var in: https://github.com/tiangolo/dockerswarm.rocks/pull/42
