### ISSUE TITLE
Q: Add oAuth2 provider instead of basic auth.

### ISSUE THREAD

**Issue by Webunity** [tiangolo/dockerswarm.rocks#23]
@tiangolo first of all; great guides! One thing i miss is the oAuth2 proxy to secure Traefik, Consul & Portainer not with basic auth, but with oAuth2 (any provider will do). Do you think it is worth a writeup?

**Comment by Webunity** [comment]
Never mind; portainer can't be used with basic auth (due to the fact they already use the `authentication` header) and the rest i found on https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik-forward-auth/keycloak/

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
