### ISSUE TITLE
Use Docker Secrets

### ISSUE THREAD

**Issue by rayrrr** [tiangolo/dockerswarm.rocks#24]
[Docker Secrets](https://docs.docker.com/engine/swarm/secrets) is a service that works exclusively with Docker Swarm and handles secrets management across a given swarm. The tutorial could be updated to use Docker Secrets where appropriate.

This would subsume #10 and the password-related part of #21.

Happy to furnish a PR.

CC: @tiangolo @vlcinsky

**Comment by andresmoschini** [comment]
@rayrrr I am having issues with the secrets and config and it is not so clear for me how to use them here. Do you have a clue?

**Comment by tiangolo** [comment]
Thanks for the suggestions. Yeah, secrets are great for the use cases they solve.

But I'm actually not sure how would you think about using them for what is in the docs. :thinking:

It would also increase complexity quite a bit and I don't see very clearly what advantage would it provide. Given that you still have to provide the values for the secrets somehow.
