### ISSUE TITLE
Swarmpit.yml update

### ISSUE THREAD

**Issue by gianlucagilardi** [tiangolo/dockerswarm.rocks#27]
Apparently swarmpit as of yesterday has added a dependency in its stack, influxdb (see: https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml)

Script of DSR should be amended accordingly...

**Comment by kekbait** [comment]
Indeed :D
Or at least just put the same image versions as those present in the previous release : https://github.com/swarmpit/swarmpit/blob/1.7/docker-compose.yml

(swarmpit/swarmpit:1.7, couchdb:2.3.0, swarmpit/agent:2.1)

**Comment by luizjr** [comment]
> Apparently swarmpit as of yesterday has added a dependency in its stack, influxdb (see: https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml)
> 
> Script of DSR should be amended accordingly...

Hello, yesterday I made a pull request to fix this.

Without these inclusion of influxdb, the graphs are not shown.
Check out the pull request: #32

**Comment by tiangolo** [comment]
Thanks @gianlucagilardi ! It is now updated with @luizjr 's PR :rocket: :tada:
