### ISSUE TITLE
Some redundant steps on swarmpit recipe

### ISSUE THREAD

**Issue by cpxPratik** [tiangolo/dockerswarm.rocks#3]
On guide https://github.com/tiangolo/dockerswarm.rocks/blob/master/docs/swarmpit.md, there is no need to point subdomain `swarmpit.your-domain.com` to the swarm cluster as it is deployed with traefik and traefik can handle to direct to correct backend based on frontend rule.

Also there is no need of exposing 8080 port to host on docker stack file https://github.com/tiangolo/dockerswarm.rocks/blob/master/docs/swarmpit.yml#L10

**Comment by cpxPratik** [comment]
`swarmpit.yml` should also be updated for this PR https://github.com/swarmpit/swarmpit/pull/319.

**Comment by tiangolo** [comment]
The domain is needed, it is used by Traefik to generate HTTPS certificates for it. And it's used inside of the Docker Compose/Stack file: https://github.com/tiangolo/dockerswarm.rocks/blob/master/docs/swarmpit.yml#L27

**Comment by cpxPratik** [comment]
@tiangolo I mean this step https://github.com/tiangolo/dockerswarm.rocks/blame/master/docs/swarmpit.md#L19, I just point domain example.com, not each of the subdomains.

**Comment by tiangolo** [comment]
Yep. But that doesn't work for everyone, not everyone set a wildcard domain with everything pointing to their cluster.

For example, someone might need to have a frontend deployed to Netlify, instead of the Docker Swarm mode cluster. So, a wildcard with `*.example.com` wouldn't work in this case.

Still, that's why it says:

> [...] Make sure that your DNS records point [...]

As you might achieve that with a wildcard. It doesn't require you to create a new DNS record, just to make sure that it works before deployment.

**Comment by cpxPratik** [comment]
Come to think of it, we do point each subdomain manually on prod since the some other subdomain is long been used for an important service. Thanks for the reply. All of the recipes here are very helpful.

**Comment by cpxPratik** [comment]
On [this comment](https://github.com/tiangolo/dockerswarm.rocks/issues/3#issuecomment-470508875), there should be some mention of `app` being default service name so if the service name is changed it should be overridden by environment variable. I did not want to create PR before specifying the issue. ref: https://github.com/swarmpit/agent/blob/adff5c79871ee8f7edac3b61febb4b903aaba0e8/setup/args.go#L17

**Comment by tiangolo** [comment]
Hmm, I'm not sure I understand what you mean...

**Comment by cpxPratik** [comment]
If the service name is not `app` such as if it is `swarmpit-app`, then swarmpit agent cannot connect to swarmpit. ref: https://github.com/swarmpit/swarmpit/pull/319

**Comment by tiangolo** [comment]
Hmm, I don't see a case where that would happen here.
