### ISSUE TITLE
Add T.A.D.S. to Project Generators section

### ISSUE THREAD

**Issue by Thomvaill** [tiangolo/dockerswarm.rocks#30]
Hi!
I love your website: it is clear, the name is fun, it catches the attention, and most of all: it is precious learning material! It's good to see good practices promoted like that.

However, during my past experience with Docker Swarm as small team leader, I noticed:
- There is a lack of good examples of well-organized Infrastructure as Code repositories
- It is hard to make developers use Docker, especially in a complex microservices environment
- It is quite impossible to make a dev able to reproduce production env

That's why I created the T.A.D.S. boilerplate project: https://github.com/Thomvaill/tads-boilerplate
It integrates Terraform, Ansible and Docker Swarm together to do full Infrastructure as Code.
It uses the same processes and configs to deploy locally and in production. It also lets developers test their Swarm cluster in a production-like environment with Vagrant (3 nodes).

In this project, of course, I promote Docker Swarm Rocks principles. For the moment there is only traefik which is implemented in the example, but Swarmprom and portainer will follow soon (https://github.com/Thomvaill/tads-boilerplate/issues/6).

I think this project could totally appear in your "Project Generators" section. What do you think?
Moreover, I would love to hear your feedback on my project!

Thanks!

**Comment by tiangolo** [comment]
Cool!

Would you like to create a PR with it?

**Comment by Thomvaill** [comment]
Sure! https://github.com/tiangolo/dockerswarm.rocks/pull/36
