### ISSUE TITLE
CI/CD Error

### ISSUE THREAD

**Issue by elben10** [tiangolo/dockerswarm.rocks#37]
I've followed the ci/cd tutorial, but I receive the following error message

```bash
Running before_script and script
00:02
 $ docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
 WARNING! Using --password via the CLI is insecure. Use --password-stdin.
 error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 169.XXX.XXX.XXX:53: no such host
```
It seems like it cannot connect to docker. I've attached the docker socket both to the gitlab runner container as well as to the gitlab runner binary within the container

**Comment by elben10** [comment]
Shared runners was enabled. Disabling shared runners made my runner pick up the jobs

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
