### ISSUE TITLE
CI/CD Error

### ISSUE THREAD

**Issue by nitinheadrun** [tiangolo/dockerswarm.rocks#43]
I have disabled the shared runners. I set up gitlab-runner inside docker container on my cloud server. I can see the runner listed in settings -> CI/CD -> Runners.
But it is giving error:- error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 213.133.100.100:53: no such host

**Comment by tiangolo** [comment]
It seems like your GitLab runner doesn't have access to Docker. Make sure you create it in a manager node and with the Docker sock volume mounted.

**Comment by iAnanich** [comment]
I have the same issue, with Docker socket being mounted.

**Comment by iAnanich** [comment]
update: I tried a bit different approach (follow instructions from [here](https://docs.gitlab.com/runner/register/index.html#docker) after creation of docker container for ci runner), but still have same issue.

**Comment by iAnanich** [comment]
That was my mistake - I didn't mount Docker socket.

**Comment by iAnanich** [comment]
So I used interactive registration shown in GitLab guidelines, which worked until recently when I discovered same problem again.
It appears that not only Docker has to be mounted, but although runner must be configured to use it.

Probably, docker socket mounting is not enough once you register more than one runner on same container/service/volume.
So to make it work, make sure that in runner's config.toml (can be found in volume's root), for all you runners `volumes` property has docker socket:
```
# runners defintion
[[runners]]
  volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
  # other properties not mentioned here
```
