### ISSUE TITLE
Is a label constraint strictly necessary?

### ISSUE THREAD

**Issue by Midnighter** [tiangolo/dockerswarm.rocks#48]
In the docs for the traefik service it is suggested to set a label constraint. The idea being that in stacks with multiple services, only one of them would have said label.

From the `traefik.yml`:

```yml
      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
```

I wonder if that is really necessary since services are not exposed by default. So traefik needs to be enabled explicitly on a service. Additionally, there is the `traefik-public` external network and as is shown, e.g., for the portainer docker-compose.yml, only the exposed service would be on that network.

The node based constraints for the volumes make a lot of sense, of course.

**Comment by tiangolo** [comment]
This is mainly for the use cases where you have other Traefik instances in your cluster, for an intra-stack load balancer.

For example, to handle traffic coming to `/dashboard` and `/api` with an intra-stack Traefik that then redirects to a service `frontend` and a service `backend`.

This would be especially (needed) for something like: https://github.com/tiangolo/full-stack-fastapi-postgresql

**Comment by Midnighter** [comment]
Cheers, thank you for the reply.
