### ISSUE TITLE
Address persistence more clearly

### ISSUE THREAD

**Issue by maxgashkov** [tiangolo/dockerswarm.rocks#49]
Many of the steps in Docker Swarm Rocks manuals assume that some part of the management architecture or even ingress (Traefik) is deployed on the single host, usually one the management nodes, due to volume persistence.

This effectively makes this node a SPOF, what Docker Swarm is especially designed to avoid.

I do understand that data persistence is a cursed topic, but shouldn't this at least be discussed somewhere in the documentation?

**Comment by tiangolo** [comment]
Hmm, what do you have in mind specifically? 

Traefik EE can support HTTPS with Let's Encrypt on multiple nodes with HA, but the community version currently can't.

Another option is to use Kubernetes and set up a system like described here: https://docs.traefik.io/providers/kubernetes-ingress/#letsencrypt-support-with-the-ingress-providers

**Comment by maxgashkov** [comment]
Judging by the fact that Traefik's website does not list the price, it's probably outside of reach for the target audience of this set of manuals. Using kubernetes is outside of scope too.

I'm suggesting at least mentioning some solution to this native to docker swarm, like rex-ray plugin for cloud storage providers.

**Comment by tiangolo** [comment]
I haven't tried Rex ray personally, and it seems it's not very actively maintained (and the website seems to be down).

I think it would be great to have other options, but I personally don't know of any.

**Comment by Bogdan1001** [comment]
@maxgashkov I think for certs management you can use  some cloud provider load balancer like Digital Ocean load balancer and for the service discovery in the cluster keep use Traefik.
