### ISSUE TITLE
add distributid mode

### ISSUE THREAD

**Issue by Blaiserman** [tiangolo/dockerswarm.rocks#5]
add 3 node distributid version of the config with persistent-storage.

**Comment by tiangolo** [comment]
I'm sorry, I'm not sure I understand what is the issue.

**Comment by Blaiserman** [comment]
your deployment is based on a single nod swarm, but in real word it would be a 3 nod or a 5 nod cluster, with some kind of distributid persistent-storage

**Comment by tiangolo** [comment]
Hmm, not really, it's in the tutorial in the main page: https://dockerswarm.rocks/#add-manager-nodes-optional

Everything is designed to work from one single node to an arbitrary number of nodes.
