### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ramonck** [tiangolo/dockerswarm.rocks#53]
@tiangolo I came here to thank you for your work and your site. I started playing with docker swarm a little while ago and you have the best site out there, I was about to study the portainer to implement it as well because I wanted to see the features of it and you have it all ready on your site, as well as the traefik which I was about to do it all on my own and you have it all chewed and I'm just copying and pasting because the swarm is so awesome that it has it for you to really just copy and paste a docker-compose that's what I saw as the nature of it and you have it setup beautifully.

You're the man, thank you!

Best wishes.

**Comment by tiangolo** [comment]
Thanks a lot! It's very nice to check a new issue notification and find this message. :smile:

Thanks for taking the time to write it. :coffee: :cake:
