### ISSUE TITLE
Adding additional services to swarmprom and Prometheus

### ISSUE THREAD

**Issue by danieljfarrell** [tiangolo/dockerswarm.rocks#56]
I have successfully got the stack up and running. I've added some additional services to the stack,

    docker stack deploy -c service1.yml service1

This service publishes metrics which can be scraped by Prometheus.

Is the process of adding services _outside_ of those defined in `swarmprom.yml` documented anywhere?

Has anybody tried?

**Comment by tiangolo** [comment]
I imagine you solved it, thanks for closing the issue! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
