### ISSUE TITLE
Worker node doesn't have TLS

### ISSUE THREAD

**Issue by BoxOfCereal** [tiangolo/dockerswarm.rocks#57]
The worker node does not have TLS enabled when I go to it's hostname/subdomain `sub.example.com` and `traefik.example.com` does not bring me to the page described in this section `https://dockerswarm.rocks/traefik/#user-interface` only `sys.traefik.example.com` works, with TLS, however.

**Comment by tiangolo** [comment]
Did you copy all the configs and followed the full tutorial until the end?

I'm not sure if I updated the tutorial at some point after you created this issue, there might be new information too 😅 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
