### ISSUE TITLE
HealthChecks

### ISSUE THREAD

**Issue by funkel1989** [tiangolo/dockerswarm.rocks#58]
Hello,

I've found docker swarm very helpful when it comes to learning about docker and docker swarm. Your stack was the beginning of most of my home automation back in 2019. One thing that seems to be missing though is health checks. When the traefik UI container shut down for instance it stayed down until I manually had to restart it. Not really knowing much about docker-compose and docker outside of what you have here, is there a way to do health checks in the compose files?

**Comment by decentral1se** [comment]
It ain't easy to grok but it's worth diving into the docs for this one:

- https://docs.docker.com/engine/reference/builder/#healthcheck
- https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by tiangolo** [comment]
I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
