### ISSUE TITLE
Repo for dockerswarm.rocks swarm setup?

### ISSUE THREAD

**Issue by mjmare** [tiangolo/dockerswarm.rocks#6]
The recipes in DockerSwarm.rocks are very useful and educational. 
Maybe I'm missing something, but I can't find the repo for the main swarm setup (with consul). For the individual recipes I follow the links for the project generators, but for the main setup I could not find it. 

I wanted to look into the compose files etc to find out how Consul is actually used. It is not clear to me as to why you would need Consul. Docker swarm supports distribution of configs and secrets. It would be nice if you could expand on that choice a little bit. 

Again, thanks for this awesome resource.

**Comment by tiangolo** [comment]
Hey @mjmare, I'm glad it's being useful.

Consul is specifically for Traefik. The docs are here: https://dockerswarm.rocks/traefik/

They are derived and updated from the docs in Traefik here: https://docs.traefik.io/user-guide/swarm/

**Comment by mjmare** [comment]
Ah, OK. Maybe add this to the docs?

**Comment by tiangolo** [comment]
It could be. Wanna write a PR? :smile:
