### ISSUE TITLE
What would be the purpose of having Portainer when we have Swarmpit

### ISSUE THREAD

**Issue by badihi** [tiangolo/dockerswarm.rocks#62]
I've followed your amazing guide on setting-up a docker swarm environment. Now I have a cluster with `traefik` and `swarmpit`. I noticed that you have a guide on `Portainer`, too. I'm happy with the stack (except for some instability that I occasionally get from swarmpit). So I'm curious, what would be the benefit of installing `Portainer` when `swarmpit` is already installed? Does it offer any more features? Or do you recommend replacing it with that?

**Comment by JuryA** [comment]
Good question -  I think that this project started with Portainer and depends on it across all tutorials. Both IMHO are still in development and new and new features are implemented. I'm not sure, if swarmpit support multi-tenancy, etc.

**Comment by tiangolo** [comment]
Thanks for the patience! And that's a good point, I didn't have a clear favorite and I was mainly exposing both alternatives.

Nevertheless, I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
