### ISSUE TITLE
Wrong background color when docker swarm.rocks render in Web tab in MS Teams in dark mode

### ISSUE THREAD

**Issue by JuryA** [tiangolo/dockerswarm.rocks#63]
When you add the **Web** tab pointing to [https://dockerswarm.rocks]() in a **dark mode** in **Microsoft Teams**, the **background color of the page is dark but text color is statically configured as black** which is a bug. To solve this issue **both should be defined or neither**. Affects all (the mobile and desktop) versions. (Most probably affects more clients/browsers in dark mode generally.)

![image](https://user-images.githubusercontent.com/11990780/101464715-4a777e00-393f-11eb-8370-e1385643f062.jpeg)

**Comment by tiangolo** [comment]
Thanks for the patience! I just deprecated this website. 🥲 

Nevertheless, I just updated the whole docs setup, new versions of MkDocs Material, etc. There's a chance that's already fixed now.
