### ISSUE TITLE
Multi domains

### ISSUE THREAD

**Issue by nbaglietto** [tiangolo/dockerswarm.rocks#64]
Hello I followed all your guides but there is something that I can not understand how to do in the variables I declare a domain type xxx.aaaaaaa.com
and it works fine but I want that bringfik to manage other domains like xxx.aaaaa.net and also domains that I have working on my local network like xxx.aaa.lan, how should I do this?
Thank you

**Comment by tiangolo** [comment]
Hey there!

For multiple domains, you would be able to do that following the guides. For local domains, I'm not sure, I don't think I've solved that problem.

Now, I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
