### ISSUE TITLE
error localhost

### ISSUE THREAD

**Issue by nbaglietto** [tiangolo/dockerswarm.rocks#66]
### I can't access local domains
---------------------------------------------------------
```

> `version: '3'
> services:
>     inventario:
>         image: nahuelbaglietto/php7.4-apache:latest
>         networks:
>           - datos
>           - traefik-public
>         volumes:
>           - /mnt/www/html/inventario:/var/www/html
>     deploy:
>       labels:
>         - "traefik.enable=true"
>         - "traefik.http.routers.inventario.rule=Host(`inventario.espaciomemoria.lan`)"
>         - "traefik.http.routers.inventario.entrypoints=http"
>         - "traefik.http.services.inventario.loadbalancer.server.port=80"
> networks:
>   traefik-public:
>     external: true
>   datos:
>     external: true`
> 

```
### 
when entering http: //inventario.espaciomemoria.lan =
-------------------------
The inventory.space.lan page has rejected the connection.
Try to:

Check connection
Check proxy and firewall
ERR_CONNECTION_REFUSED
---------------------------------------------

**Comment by tiangolo** [comment]
Thanks for the patience. It seems you have a local domain, you would probably need to configure it in your internal network, you would have to debug that first.

I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
