### ISSUE TITLE
Not working with Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by lowercase00** [tiangolo/dockerswarm.rocks#67]
Seems that `/etc/hostname` is immutable in Ubuntu 20.04, so the command `echo $USE_HOSTNAME > /etc/hostname` gives permission denied (even with sudo). Tried `sudo chattr +i /etc/hostname` but also didn't work.

**Comment by lowercase00** [comment]
Ok, I think I got it:

```
$ sudo chattr +i -f "$(realpath /etc/hostname)"
$ sudo echo $USE_HOSTNAME > /etc/hostname
   -bash: /etc/hostname: Operation not permitted
$ sudo hostnamectl set-hostname $USE_HOSTNAME
    Could not set property: Access denied  ### This is strange
$ hostname
     myhostname.example.com ### says access denied but seems to work...
```

**Comment by Trymzet** [comment]
You can follow [this](https://askubuntu.com/a/516898) Stackoverflow answer (`hostnamectl set-hostname $USE_HOSTNAME`).

**Comment by tiangolo** [comment]
Thanks for reporting back! If you solved the problem, you can close the issue. ✔️ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
