### ISSUE TITLE
Swarmpit on ARM

### ISSUE THREAD

**Issue by tylerlittlefield** [tiangolo/dockerswarm.rocks#70]
I was able to get swarmpit stack working with the tiniest change:

`image: couchdb:2.3.0` -> `image: couchdb:2.3.1`

Just letting others know in case they want to get this stack running on a Pi cluster.

**Comment by tiangolo** [comment]
Thank you! And thanks for the patience.

I updated it here: https://github.com/tiangolo/dockerswarm.rocks/pull/114
