### ISSUE TITLE
Let's encrypt issue

### ISSUE THREAD

**Issue by PoOwAa** [tiangolo/dockerswarm.rocks#71]
I followed the steps from the documentation, but I got stuck.

In my traefik.yml I've got the necessary commands to use let's encrypt correctly:

```
  command:
     # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL?Variable not set}
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true

  labels:
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
```

When I open traefik/swarmpit, the certificates are invalid:

TRAEFIK DEFAULT CERT
Self-signed root certificate

I had created the `traefik-public-certificates` directory, and I placed an empty `acme.json` file inside it.

What did I wrong? I'm using Ubuntu 20.04 LTS on AWS EC2 instance.

**Comment by PoOwAa** [comment]
Firstly it couldn't reach my domain, because of DNS misconfiguration. So I got a self-signed cert. After the correct DNS configuration still, nothing changed, but a few hours later traefik changed the certificates under the hood. Now it is working correctly!

**Comment by tiangolo** [comment]
Thanks for coming back to report and close the issue! 🍰 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
