### ISSUE TITLE
Traefik example and its labels

### ISSUE THREAD

**Issue by openscript** [tiangolo/dockerswarm.rocks#74]
In the [Traefik example](https://dockerswarm.rocks/traefik/) I see that in the docker-compose template the labels are defined like usually. As I run into some problems with the tutorial. Is it possible that some of the labels should be deployed in:

```
deploy:
  labels:
    - ....
```

Also here this is shown like this: https://dev.to/ohffs/traefik-v2-with-docker-swarm-2cgh

Thank you for the project! I've learned many things

**Comment by tiangolo** [comment]
Cool! I think you solved it, right? If you did, then you can close the issue. ✔️ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
