### ISSUE TITLE
Traefik on 2 Manager Nodes

### ISSUE THREAD

**Issue by meeximum** [tiangolo/dockerswarm.rocks#76]
Hi,

we want to have two managers on each running a treafik service, is this possible/good?

we want to achieve High Availability of our Swarm?

best regards
Meex

**Comment by prettycode2018** [comment]
Yes

**Comment by tiangolo** [comment]
Thanks for the patience! Maybe @frugan-dev answer does it.

Nevertheless, I should let you know that I had to deprecate this website and these ideas, I would no longer recommend using Docker Swarm Mode. 🥲 

https://dockerswarm.rocks/swarm-or-kubernetes/
