### ISSUE TITLE
What are the things to look when traefik.<domain name> is not loading?

### ISSUE THREAD

**Issue by deepakpjose** [tiangolo/dockerswarm.rocks#79]
Hi Team,

Thanks for the steps to enable https using traefik. I'm new to docker and web hosting.

After following the steps in the page, I'm unable to open traefik.domain name. 
DNS record is set in my godaddy account to point to my aws address and I can see in nslookup output.

Can someone tell me the things to look when traefik.domain name gets a connection time out error?

Thanks,
Deepak

**Comment by decentral1se** [comment]
You'll want to use use `docker service logs -f <traefik-service>` to trail the logs, traefik will normally tell you all you need to know.
