### ISSUE TITLE
Any recommended FOSS projects for Docker Swarm Mode deployments?

### ISSUE THREAD

**Issue by Reinitialized** [tiangolo/dockerswarm.rocks#81]
Title pretty much says it all. I'm looking for FOSS projects which I can use as reference for building my own Swarm Mode project, and have actually found it quite difficult to locate projects since K8S is the dominating orchestrator these days.

**Comment by decentral1se** [comment]
https://git.coopcloud.tech/coop-cloud is using all swarm configs :rocket:

**Comment by tiangolo** [comment]
I should let you know, I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
