### ISSUE TITLE
[feature request] dark mode for dockerswarm.rocks

### ISSUE THREAD

**Issue by silvioprog** [tiangolo/dockerswarm.rocks#86]
Hi.

Thanks a lot for this awesome project!

So, it would be nice to allow dark mode for https://dockerswarm.rocks.

Thank you very much!

**Comment by tiangolo** [comment]
Thanks! I'll pass on this one, I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
