### ISSUE TITLE
Feature Request: Explain the roles of Portainer and Swarmpit (better)

### ISSUE THREAD

**Issue by The-Judge** [tiangolo/dockerswarm.rocks#88]
Hi there,

dockerswarm.rocks is awesome! Thank you for providing that!

When reading through it, it seems as if [Swarmpit](https://dockerswarm.rocks/swarmpit/) and [Portainer](https://dockerswarm.rocks/portainer/) do more or less the same thing. To me, it is unclear what to choose in which situation or if I need both to have the best control of all aspects of the swarm.

Since dockerswarm.rocks offer guides for both, it is unclear if they serve different sakes or if they are just two alternatives based on personal preference.

It would be great if that could be explained a bit better in the guide; you most certainly would also not set up a container for Apache, Nginx, Envoy and Traefik in any swarm without good reasons. It looks a bit like the same thing to me for those GUIs.

Best regards,
Marc

**Comment by tiangolo** [comment]
That's a good point! I didn't have a clear favorite, it would have been better.

Nevertheless, at this point, I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲 

So the website will still be up mainly for historical reasons. 🤓
