### ISSUE TITLE
Everything depends on the first node despite being in swarm mode

### ISSUE THREAD

**Issue by jherazob** [tiangolo/dockerswarm.rocks#91]
Hi! Good guides, although they have a vital flaw: If the first node falls, everything breaks. Even after i changed the Traefik placement constraint to not store the Let's Encrypt info only on node 1, still Swarmpit and Portainer break when the first node falls, despite getting automatically distributed. I'm still learning so i'm unclear yet on why. 

Can you please give this a look so that the first and most important advantage of a swarm, the fact that any node can fall without breaking the system, remains true?

Thanks!

**Comment by tiangolo** [comment]
Thanks for the patience! I should let you know, that I had to deprecate this website and ideas, I would no longer recommend Docker Swarm Mode for new projects: https://dockerswarm.rocks/swarm-or-kubernetes/ 🥲
